# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6SKENppIXxz9hKukp7zfawlkN1HLnFn

##### **Project Type**    - EDA/
##### **Contribution**    - Team
##### **Team Member 1 -** Ashika.P
##### **Team** **Member** **2** -  **Priyam**
##### **Team Member 3 -**
##### **Team Member 4 -**

# **Project Summary -**

#### **📊 Project Summary – Online Retail Data Analysis

In this project, we began exploring the Online Retail dataset, which contains transactional data from a UK-based online retail company that mainly sells unique gift items.

The dataset contains 541,909 rows and 8 columns, representing individual product transactions made by customers.

The columns in the dataset include:

InvoiceNo

StockCode

Description

Quantity

InvoiceDate

UnitPrice

CustomerID

Country

All columns are divided into three data types:

Object

float64

int64

During the initial exploration of the dataset, we observed that the dataset contains missing values and some invalid transactions such as product returns (negative quantities).

Therefore, data cleaning was performed to improve data quality. The following steps were taken:

Converted InvoiceDate column to datetime format

Removed rows with missing CustomerID values

Checked and handled negative quantities (product returns)

Created a new column TotalPrice = Quantity × UnitPrice

After cleaning the dataset, the data manipulation workflow was divided into three main stages:

1️⃣ Data Collection
2️⃣ Data Cleaning and Manipulation
3️⃣ EDA (Exploratory Data Analysis)

During the Data Collection stage, we used several basic functions and attributes to understand the dataset structure and columns.

Some of the functions used include:

head() – to display the first few rows of the dataset

tail() – to view the last few rows

info() – to check data types and missing values

describe() – to view statistical summaries of numerical columns

columns() – to list all column names

In the Data Cleaning and Manipulation stage, missing values were handled and necessary columns were created for further analysis.

In the Exploratory Data Analysis (EDA) stage, several visualizations were created to better understand the business patterns in the dataset.

These visualizations include:

Histogram to analyze quantity distribution

Scatter plot to analyze Quantity vs TotalPrice relationship

Correlation heatmap to analyze relationships between Quantity, UnitPrice and TotalPrice

Monthly sales trend analysis

Customer segmentation using RFM Analysis (Recency, Frequency, Monetary)

Through this analysis, we were able to identify customer purchasing behavior, revenue patterns, and high-value customers.

The project demonstrates how data cleaning, visualization, and customer segmentation techniques can help businesses extract meaningful insights from transaction data and support better decision-making. **

# **Project Name**    - Myntra Retail Customer Behavior Analysis

This project performs Exploratory Data Analysis (EDA) on the Online Retail dataset.
The goal is to understand customer purchasing behavior, sales trends, and product performance.
The dataset is cleaned by handling missing values, duplicates, and incorrect data types.
Further analysis includes revenue analysis, top products, customer segmentation, and RFM analysis.

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

The objective of this project is to analyze retail transaction data to:

	•	Identify top-selling products
	•	Analyze customer purchasing patterns
	•	Calculate total revenue
	•	Perform RFM analysis for customer segmentation
	•	Detect cancellation **patterns**

#### **Define Your Business Objective?**

The primary business objective of this project is to analyze online retail transaction data to understand customer purchasing behavior, identify revenue trends, and improve business decision-making.

The analysis aims to:

	•	Identify top-selling products and high-revenue categories
	•	Understand monthly and seasonal sales trends
	•	Detect cancelled transactions and their impact
	•	Segment customers using RFM (Recency, Frequency, Monetary) analysis
	•	Identify high-value and loyal customers

The insights from this analysis will help the business improve marketing strategies, customer retention, inventory planning, and revenue growth.

# **General Guidelines** : -  
This project follows a structured data analysis approach:

	1.	Data Understanding – Understanding dataset structure, variables, and business context.
	2.	Data Cleaning – Handling missing values, removing duplicates, filtering cancelled transactions, and correcting data types.
	3.	Feature Engineering – Creating new features such as Total Revenue and RFM metrics.
	4.	Exploratory Data Analysis (EDA) – Analyzing sales trends, top products, customer behavior, and country-wise performance using visualizations.
	5.	Customer Segmentation – Performing RFM analysis to categorize customers into different segments.
	6.	Business Insights & Recommendations – Providing actionable insights based on analysis.

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

"""### Dataset Loading"""

from google.colab import drive

# Load Dataset
drive.mount('/content/drive')

df=pd.read_csv('/content/drive/MyDrive/Online Retail.csv',encoding='ISO-8859-1')

"""### Dataset First View"""

df

# Dataset First Look
df.head()

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
df.shape

"""### Dataset Information"""

# Dataset Info
df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
df.duplicated().sum()

#remove duplicates
df=df.drop_duplicates()

df.duplicated().sum()

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
df.isnull().sum()

df.shape

#remove missing customerID
df = df.dropna(subset=['CustomerID'])

#remove  missing description
df=df.dropna(subset=['Description'])

#verify again
df.isnull().sum()

# Visualizing the missing values
# Plot missing values
plt.figure(figsize=(8,5))
sns.barplot(x=df.isnull().sum().index, y=df.isnull().sum().values)
plt.xticks(rotation=90)
plt.title("Missing Values Count After Cleaning")
plt.show()

df.shape

"""### What did you know about your dataset?
The dataset contained 135,037 missing values in the CustomerID column and 1,454 missing values in the Description column.
Since CustomerID is essential for customer segmentation and RFM analysis, rows with missing CustomerID were removed.
Rows with missing Description were also removed to maintain data quality.
After cleaning, the dataset contained no missing values.

A visualization of missing values confirms that there are no remaining null values in the dataset after cleaning. The dataset is now complete and ready for further analysis.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
df.columns

# Dataset Describe
df.describe()

df.describe(include='all')

"""### Variables Description
InvoiceNo – Unique invoice number assigned to each transaction.

StockCode – Unique product code.

Description – Name of the product.

Quantity – Number of units purchased per transaction.

InvoiceDate – Date and time of purchase.

UnitPrice – Price per unit of the product.

CustomerID – Unique identifier for each customer.

Country – Country where the customer resides.

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
df.nunique()

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.
#check missing values
df.isnull().sum()

#check duplicates
df.duplicated().sum()

#remove cancelled orders
#Cancelled invoices start with "C"
df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]

#Remove negative quantity
df = df[df['Quantity'] > 0]

#remove zero price
df = df[df['UnitPrice'] > 0]

#Create total price column
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']

"""### What all manipulations have you done and insights you found?

1️⃣ Checked Dataset Structure

	•	Used df.info() and df.describe()
	•	Found total records ≈ 401,604
	•	Identified missing values and data types
2️⃣ Handled Missing Values

	•	Found null values mainly in CustomerID
	•	Removed rows where CustomerID was missing

This ensures customer-level analysis (RFM) is accurate.

3️⃣ Removed Duplicate Records
  Prevents double counting of revenue.

4️⃣Removed Cancelled Orders.

	•	Cancelled invoices start with “C”
	•	Negative quantity represents returns.

This keeps only valid completed transactions

5️⃣ Removed Invalid Prices.

Ensures revenue calculation is correct.

6️⃣ Converted Data Types.

Helps in time-based analysis and grouping.

7️⃣Created New Feature (Feature Engineering
This is used to calculate revenue.)

** Insights:**
🔹 1. Customer Base

	•	Total unique customers ≈ 4,372
	•	Customers are from 37 countries
	•	Majority of customers are from United Kingdom

🔹 2. Sales Behaviour

	•	Some transactions had negative quantities (returns)
	•	Some invoices were cancelled
	•	Most purchases contain small quantities (median around 5 units)

  🔹 3. Product Insights

	•	Around 3,800+ unique products
	•	Few products generate majority of sales (Pareto principle)

🔹 4. Revenue Insights

	•	Revenue is concentrated in UK
	•	Some customers contribute significantly higher revenue (high-value customers)


🔹 5. Data Quality Observations

	•	Large number of missing CustomerID values
	•	Duplicate transactions were present
	•	Some abnormal values (negative quantity, zero price)

###Create a new column for visulaization
"""

df['TotalPrice'] = df['Quantity'] * df['UnitPrice']

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], dayfirst=True)

"""## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

**Chart - 1 Monthly Sales Trend(Time vs Revenue)**
"""

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

df['TotalPrice'] = df['Quantity'] * df['UnitPrice']

df['Month'] = df['InvoiceDate'].dt.to_period('M')

monthly_sales = df.groupby('Month')['TotalPrice'].sum()

monthly_sales.plot(figsize=(10,5))
plt.show()

"""##### 1. Why did you pick the specific chart?

•	Shows seasonality.

•	Identify peak sales month.

•	Detect growth trend.

##### 2. What is/are the insight(s) found from the chart?

Sales increased towards the end of the year, indicating seasonal buying behavior.
"""

monthly_sales = df.groupby(df['InvoiceDate'].dt.to_period('M'))['TotalPrice'].sum()

monthly_sales.plot(figsize=(10,5))

plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.show()

"""**Chart - 2   Top 10 Countries by Revenue**"""

# Chart - 2 visualization code
top_countries = df.groupby('Country')['TotalPrice'].sum().sort_values(ascending=False).head(10)
top_countries.plot(kind='bar')

"""##### 1. Why did you pick the specific chart?

•	UK dominates revenue.

•	Few countries contribute majority of sales.

##### 2. What is/are the insight(s) found from the chart?

Revenue is highly concentrated in the United Kingdom.

**Chart - 3 Top 10 Products**
"""

# Chart - 3 visualization code
top_products = df.groupby('Description')['Quantity'].sum().sort_values(ascending=False).head(10)
top_products.plot(kind='bar')

"""##### 1. Why did you pick the specific chart?

•	Identify best-selling items.

•	Helps inventory decisions.

##### 2. What is/are the insight(s) found from the chart?

Best selling items

#### **Chart - 4 Distribution of Order Quantity**
"""

# Chart - 4 visualization code
df['Quantity'].plot(kind='hist',bins=50)

"""##### 1. Why did you pick the specific chart?

•	Most orders are small quantity.

•	Few bulk purchases (outliers).

##### 2. What are the insight(s) found from the chart?

.Most orders have small quantities (around 1–10 items).

.There are some very large quantities — these may be bulk purchases or wholesale orders.

.There are also negative quantities, which usually represent returns or cancelled orders in this retail dataset.

**Chart - 5 Quantity vs TotalPrice**
"""

# Chart - 5 visualization code
plt.scatter(df['Quantity'], df['TotalPrice'])
plt.xlabel('Quantity')
plt.ylabel('Total Price')
plt.title('Quantity vs Total Price')
plt.show()

"""##### 1. Why did you pick the specific chart?

There is a positive relationship between quantity purchased and total revenue.

##### 2. What is/are the insight(s) found from the chart?

•	Higher quantity → higher revenue.

•	Some outliers exist.

**Chart - 6 Unit Price vs Quantity**
"""

# Chart - 6 visualization code
plt.scatter(df['UnitPrice'], df['Quantity'])
plt.show()

"""##### 1. Why did you pick the specific chart?

•	Expensive products usually bought in small quantities.

•	Cheap products bought in bulk.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

#### **Chart - 7 Correlation Matrix**
"""

# Chart - 7 visualization code
df[['Quantity', 'UnitPrice', 'TotalPrice']].corr()

"""##### 1. Why did you pick the specific chart?

•	Shows numerical relationship strength

•	Helps explain patterns mathematically

##### 2. What is/are the insight(s) found from the chart?

.Customers buy cheap products in bulk

.Expensive items are bought less frequently

.Revenue depends on both quantity and price
"""

# Chart - 10 visualization code
sns.boxplot(x=df['TotalPrice'])
plt.title("Total Price Boxplot")
plt.show()

"""#### **Chart - 11 Heatmap(Correlation)**"""

# Chart - 11 visualization code
sns.heatmap(df[['Quantity','UnitPrice','TotalPrice']].corr(),annot=True)
plt.title("Correlation Heatmap")
plt.show()

"""A heatmap displays correlation values using colors.

Dark color → strong relationship

Light color → weak relationship

annot=True means show the correlation numbers on the chart.

Example visualization idea:

            Quantity  UnitPrice  TotalPrice
Quantity       1.00      -0.10        0.70
UnitPrice     -0.10       1.00        0.45
TotalPrice     0.70       0.45        1.00

#### **Scatter Plot(Relationship)**
"""

# Chart - 12 visualization code
plt.scatter(df['Quantity'], df['TotalPrice'])
plt.xlabel('Quantity')
plt.ylabel('Total Price')
plt.title('Quantity vs Total Price')
plt.show()

"""📦 1. Customer Buying Behavior

Most points will appear around small quantities like:
Meaning most customers buy small orders.  
📈 2. Bulk Purchases

Some points appear far right:

These represent bulk buyers or wholesalers.

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

The objective is to analyze online retail transaction data to understand customer behavior, sales performance, and revenue drivers in order to improve marketing strategy, customer retention, and overall profitability.

🔹 1. Revenue Concentration

	•	Majority of revenue comes from United Kingdom
	•	Few countries contribute very little revenue

🔹 2. Customer Distribution

	•	Around 4,000+ active customers
	•	Small group of customers generate large revenue (high Monetary value)

🔹 3. Sales Pattern

	•	Seasonal spikes (especially year-end months)
	•	Most purchases are low quantity
	•	Few bulk orders create high revenue spikes

🔹 4. Product Insights

	•	Few products are best sellers (80/20 rule)
	•	Some products rarely sell
  •	Many one-time buyers

**Final Business Recommendations**

The analysis shows that revenue is highly concentrated among a small group of loyal customers and primarily within the UK market. To achieve sustainable growth, the company should focus on customer retention strategies, reactivation campaigns for inactive customers, geographical expansion, and promotional strategies around high-performing products and peak seasons. Implementing RFM-based segmentation can significantly improve targeted marketing efficiency and increase overall profitability.

# **Conclusion**

I recommend implementing a customer segmentation strategy using RFM analysis, prioritizing high-value customer retention, targeting at-risk customers through personalized campaigns, and expanding into underperforming international markets to diversify revenue streams.
"""

